import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'newrxjs';
import { Router } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import {baseUrl} from './index';
import {TicketBody} from '../models/index';

@Injectable({
  providedIn: 'root',
})
export class TicketService {
  ticketId = new BehaviorSubject<string>("");
  mainIssueId = new BehaviorSubject<string>("");
  isTicketSubmitSuccess = new BehaviorSubject<boolean>(false);

  // Mockup
  ticketDetail = new BehaviorSubject<any>([
    {
      ticket_no: 'GA0000001',
      subject: 'KKKKKKKKKKKKKKKKKKKKK',
      status: 'Complete',
      create_date: 'MM/DD/YYYY HH:MM PM',
      description:
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
      support: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    },
    {
      ticket_no: 'RP0000004',
      subject: 'KKKKKKKKKKKKKKKKKKKKK',
      status: 'Pending',
      create_date: 'MM/DD/YYYY HH:MM PM',
      description:
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
      support: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    },
    {
      ticket_no: 'XXXXXXXXXXXXXX',
      subject: 'KKKKKKKKKKKKKKKKKKKKK',
      status: 'Complete',
      create_date: 'MM/DD/YYYY HH:MM PM',
      description:
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
      support: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    },
    {
      ticket_no: 'XXXXXXXXXXXXXX',
      subject: 'KKKKKKKKKKKKKKKKKKKKK',
      status: 'Complete',
      create_date: 'MM/DD/YYYY HH:MM PM',
      description:
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
      support: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    },
    {
      ticket_no: 'XXXXXXXXXXXXXX',
      subject: 'KKKKKKKKKKKKKKKKKKKKK',
      status: 'Complete',
      create_date: 'MM/DD/YYYY HH:MM PM',
      description:
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
      support: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    },
    {
      ticket_no: 'XXXXXXXXXXXXXX',
      subject: 'KKKKKKKKKKKKKKKKKKKKK',
      status: 'Complete',
      create_date: 'MM/DD/YYYY HH:MM PM',
      description:
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
      support: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    },
    {
      ticket_no: 'XXXXXXXXXXXXXX',
      subject: 'KKKKKKKKKKKKKKKKKKKKK',
      status: 'Complete',
      create_date: 'MM/DD/YYYY HH:MM PM',
      description:
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
      support: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    },
    {
      ticket_no: 'XXXXXXXXXXXXXX',
      subject: 'KKKKKKKKKKKKKKKKKKKKK',
      status: 'Complete',
      create_date: 'MM/DD/YYYY HH:MM PM',
      description:
        'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
      support: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    },
  ]);

  constructor(private router: Router, private http: HttpClient) {}

  toSubmitSuccessTicketPage() {
    this.isTicketSubmitSuccess.next(true);
    this.router.navigate(['/ticket/submit-success']);
  }

  getTicketDetail() {
    return this.http.get<any>(`${baseUrl}/ticket/readall`);
  }
  getSingleTicketDetail(id: string) {
    return this.http.get<any>(`${baseUrl}/ticket/read/${id}`);
  }
  getGameList() {
    return this.http.get<any>(`${baseUrl}/game/readall`);
  }
  getMainIssue() {
    return this.http.get<any>(`${baseUrl}/main_issue/readall`);
  }
  getSubIssue() {
    return this.http.get<any>(`${baseUrl}/sub_issue/readall`);
  }

  createTicket(body: TicketBody) {
    return this.http.post<any>(`${baseUrl}/ticket/create`, body);
  }

  getTicketId() {
    return this.ticketId.asObservable();
  }
  getIsTicketSubmitSuccess() {
    return this.isTicketSubmitSuccess.asObservable();
  }

}
