# ---------------------------------------------------------------------------------------------
server {
    listen 80;

    if ($bad_client) { return 444; }

    ## Extra protection
    location ~ ^/([^/])+\.(sh|pl|py|lua|inc|swp|phar|php_|log|ini|md|sql|conf|yml|php|zip|tar|.+gz)$ { deny all; }
    location ~ /\.(svn|git|hg|htpasswd|bash|ssh) { deny all; }
    location ~ /\. { deny all; }
    location ~* /(adminer|indexator) { deny all; }

    # web app
    location / {
        root   /usr/share/nginx/mygg;
        try_files $uri $uri/ /index.html;
        index  index.html;
    }

    ## web service
    location /backend {
        proxy_pass http://192.168.120.106:3000;
        client_max_body_size 10M;

        proxy_http_version 1.1;
        proxy_read_timeout 300s;
        proxy_connect_timeout 300s;
        proxy_intercept_errors on;
        proxy_buffering off;
        
        proxy_set_header   Connection         "upgrade";
        proxy_set_header   Upgrade            $http_upgrade;
        proxy_set_header   Host               $host;
        proxy_set_header   X-Real-IP          $remote_addr;
        proxy_set_header   X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto  $scheme;
        proxy_set_header   Cookie             $http_cookie;
    }
} 
    